// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EmpregosParaDocumentDataSlicesSlice = GerarSlice;

/**
 * Content for Empregos Pará documents
 */
interface EmpregosParaDocumentData {
  /**
   * Slice Zone field in *Empregos Pará*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: empregos_para.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EmpregosParaDocumentDataSlicesSlice> /**
   * Meta Description field in *Empregos Pará*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: empregos_para.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Empregos Pará*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: empregos_para.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Empregos Pará*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: empregos_para.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Empregos Pará document from Prismic
 *
 * - **API ID**: `empregos_para`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmpregosParaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EmpregosParaDocumentData>,
    "empregos_para",
    Lang
  >;

export type AllDocumentTypes = EmpregosParaDocument;

/**
 * Primary content in *Gerar → Default → Primary*
 */
export interface GerarSliceDefaultPrimary {
  /**
   * Curriculos field in *Gerar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gerar.default.primary.curriculos
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  curriculos: prismic.ImageField<never>;
}

/**
 * Default variation for Gerar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GerarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GerarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gerar*
 */
type GerarSliceVariation = GerarSliceDefault;

/**
 * Gerar Shared Slice
 *
 * - **API ID**: `gerar`
 * - **Description**: Gerar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GerarSlice = prismic.SharedSlice<"gerar", GerarSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EmpregosParaDocument,
      EmpregosParaDocumentData,
      EmpregosParaDocumentDataSlicesSlice,
      AllDocumentTypes,
      GerarSlice,
      GerarSliceDefaultPrimary,
      GerarSliceVariation,
      GerarSliceDefault,
    };
  }
}
